name: Feature Request
description: File a bug report
title: "[Feature Request]: "
labels: ["new", "suggestion"]
assignees:
  - Ej-leone
  - bkimotho
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info? What's your Telegram handle?
      placeholder: kotanipaysupport
    validations:
      required: false
  - type: textarea
    id: what-feature
    attributes:
      label: What new feature would you like to suggest?
      description: 
      placeholder: 
      value: 
    validations:
      required: true
  - type: dropdown
    id: product
    attributes:
      label: Product
      description: Where do you propose the feature to be included?
      options:
        - API (Default)
        - USSD
        - Web App
        - Mobile App
        - WhatsApp bot
        - dapp
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://docs.kotanipay.com/fundamentals/code-of-conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
